### ISSUE TITLE
Deprecation warnings...

### ISSUE THREAD

**Issue by merriam** [yathit/ydn-db#49] opened 2015-04-28 06:33 UTC
On recent versions of Chrome, I get warnings "'webkitIDBRequest' is deprecated. Please use 'IDBRequest' instead.".  While it appears to be a simple fix, I leave it to someone who already knows this code.

**Comment by yathit** [comment] 2015-04-29 04:41
Duplicate of #45

**Closed by yathit** 2015-04-29 04:41 UTC
